
library(raster)
library(rgdal)


### R code to calculate climatic variables mean of species distribution area (IUCN polygons) developed by Raquel Divieso.

#Opening 2.5m rasters of bioclimatic variables from WorldClim
env<-getData("worldclim", var="bio", res=2.5)
newproj <- "+proj=cea"
env_ok <- projectRaster(env, crs=newproj)

my_fun<-function(x){
  shaa <- sha[sha$BINOMIAL == x, ]
  ras_crop<-crop(env_ok,shaa)
  Env_shape1<-mask(ras_crop, shaa)
  bio1<-mean(as.matrix(Env_shape1$bio1), na.rm=T)
  bio5<-mean(as.matrix(Env_shape1$bio5), na.rm=T)
  bio6<-mean(as.matrix(Env_shape1$bio6), na.rm=T)
  bio12<-mean(as.matrix(Env_shape1$bio12), na.rm=T)
  bio16<-mean(as.matrix(Env_shape1$bio16), na.rm=T)
  bio17<-mean(as.matrix(Env_shape1$bio17), na.rm=T)
  spp<-as.character(x)
  xx<-cbind(spp, bio1, bio5, bio6, bio12,  bio16, bio17)
  xx
}

#all clade shapefiles were obtained using the IUCN download system. All forms were processed at QGIS where introduced and uncertain ranges have been omitted. 
#The range area was calculated using QGIS 3.8.3 (QGIS Development Team 2020) on cylindrical equal-area projection.
##### Ciconiiformes
sha<- readOGR("~/birds_ranges/Ciconiiformes/data_0.shp") 
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
Sys.time()
result <- sapply(unique, my_fun)
Sys.time()
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Ciconiiformes_var.csv" )
# Anura
sha<- readOGR("~/birds_ranges/Anura/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Anura_var.csv" )
# Caudata
sha<- readOGR("~/birds_ranges/Caudata/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Caudata_var.csv" )
# Gymnophiona
sha<- readOGR("~/birds_ranges/Gymnophiona/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
Sys.time()
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Gymnophiona_var.csv" )
# Passeriformes
sha<- readOGR("~/birds_ranges/Passeriformes/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Passeriformes_var.csv" )
# Piciformes
sha<- readOGR("~/birds_ranges/Piciformes/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Piciformes_var.csv" )
# Columbiformes
sha<- readOGR("~/birds_ranges/Columbiformes/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Columbiformes_var.csv" )
# Psittaciformes
sha<- readOGR("~/birds_ranges/Psittaciformes/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Psittaciformes_var.csv" )
# Chiroptera
sha<- readOGR("~/birds_ranges/Chiroptera/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Chiroptera_var.csv" )
# Primates
sha<- readOGR("~/birds_ranges/Primates/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Primates_var.csv" )
# Carnivora
sha<- readOGR("~/birds_ranges/Carnivora/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Carnivora_var.csv" )
# Cetartiodactyla
sha<- readOGR("~/birds_ranges/Caudata/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Gymnophiona_var.csv" )
# Diprotodontia
sha<- readOGR("~/birds_ranges/Diprotodontia/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Gymnophiona_var.csv" )
# Anguimorpha
sha<- readOGR("~/birds_ranges/Diprotodontia/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Gymnophiona_var.csv" )
# Gekkota
sha<- readOGR("~/birds_ranges/Gekkota/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Gekkota_var.csv" )
# Iguania
sha<- readOGR("~/birds_ranges/Iguania/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Iguania_var.csv" )
# Lacertoidea
sha<- readOGR("~/birds_ranges/Lacertoidea/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Lacertoidea_var.csv" )
# Scincoidea
sha<- readOGR("~/birds_ranges/Scincoidea/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/Scincoidea_var.csv" )
# Serpentes
sha<- readOGR("~/birds_ranges/Serpentes/data_0.shp")
sha<- spTransform(sha, CRS("+proj=cea +ellps=WGS84"))
unique <- unique(sha$BINOMIAL)
length(unique)
result <- sapply(unique, my_fun)
df <- data.frame(matrix(unlist(result), nrow=length(unique), byrow=T),stringsAsFactors=FALSE)
colnames(df)<-c("spp", "bio1", "bio5", "bio6", "bio12", "bio16", "bio17")
write.csv(df, "~/Var_bioclim_by_shape/ Serpentes_var.csv" )





